version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

    networks:
      - backbone
      - private
networks:
  backbone:
    external: true
  private:
    external: false
